all:
  children:
    kubernetes:
      children:
        k8s-masters:
          hosts:
            kubm1:
              ansible_host: 192.168.56.11
            kubm2:
              ansible_host: 192.168.56.12
            kubm3:
              ansible_host: 192.168.56.13
        k8s-workers:
          hosts:
            kubw1:
              ansible_host: 192.168.56.14
            kubw2:
              ansible_host: 192.168.56.15

        jenkins:
          hosts:
            jenkins:
              ansible_host: 192.168.56.16
 
