---
# defaults file for kubernetes

kubernetes_prerequisites_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - lsb-release
  - bridge-utils

kubernetes_version: 1.28.5-1.1
